version: '3.8'

services:
  app:
    container_name: remix-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "${PORT:-3000}:3000"