version: '3.8'

services:
  app:
    container_name: remix-app-dev
    build:
      context: .
      dockerfile: dev/Dockerfile
    env_file:
      - .env
      - .env.development
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules